version: "3.6"
services:
  ${SERVICE_NAME}:
    hostname: ${NETWORK_NAME}_${SERVICE_NAME}
    container_name: ${NETWORK_NAME}_${SERVICE_NAME}
    image: mariadb:11.4.3
    networks:
      default:
        aliases:
          - mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/logs/mysql
    restart: always
networks:
  default:
    name: ${NETWORK_NAME}
    external: true

