#!/bin/bash

install_service() {

  echo "Installation von Service mariadb in Netzwerk '${NETWORK_NAME}'"
  SERVICE_NAME=mariadb
  echo "Service-Name=${SERVICE_NAME}"

  if [ -z "$MARIADB_ROOT_PASSWORD" ] ; then
    read -p "mariadb Root Passwort:" -s MARIADB_ROOT_PASSWORD
  else
    echo "Use pre-defined MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:1:5}..."
  fi
  echo "MARIADB_ROOT_PASSWORD=\"${MARIADB_ROOT_PASSWORD}\"" >> ${USER_DIR}/networks/${NETWORK_NAME}/env

  SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

  if [ -d "$SERVICE_PATH" ]; then
    echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
    return 1
  fi

  mkdir -p ${SERVICE_PATH}
  cp -r ${USER_DIR}/kvwmap-server/service-templates/mariadb/directory_template/* ${SERVICE_PATH}
  cp    ${USER_DIR}/kvwmap-server/service-templates/mariadb/compose-template.yml ${SERVICE_PATH}/

  chown -R 999:gisadmin ${SERVICE_PATH}/

  echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."
}
