#!/bin/bash

install_service() {

  echo "Installation von Service pgadmin in Netzwerk '${NETWORK_NAME}'"
  SERVICE_NAME=certbot
  echo "Service-Name=${SERVICE_NAME}"

  SERVICE_PATH=${USER_DIR}/networks/${NETWORK_NAME}/services/${SERVICE_NAME}

  if [ -d "$SERVICE_PATH" ]; then
    echo "Der Service existiert in dem Netzwerk bereits. Starten Sie erneut und wählen Sie einen anderen Namen!"
    return 1
  fi

  mkdir -p ${SERVICE_PATH}

  cp -i -r ${USER_DIR}/kvwmap-server/service-templates/certbot/compose-template.yml ${SERVICE_PATH}/

  echo "Installation von ${SERVICE_NAME} in ${NETWORK_NAME} beendet."
}

