#!/bin/bash
CRONTAB_DIR="/var/www/cron"

CRONTAB_USER=gisadmin
CRONTAB_FILE="$CRONTAB_DIR/crontab_$CRONTAB_USER"
cat $CRONTAB_DIR/$CRONTAB_USER/* > $CRONTAB_FILE
if [ -s $CRONTAB_FILE ] ; then
  crontab -u $CRONTAB_USER $CRONTAB_FILE
  #echo "`date` Update $CRONTAB_USER crontab." >> /var/www/logs/cron/cron.log
fi

CRONTAB_USER=root
CRONTAB_FILE="$CRONTAB_DIR/crontab_$CRONTAB_USER"
cat $CRONTAB_DIR/$CRONTAB_USER/* > $CRONTAB_FILE
if [ -s $CRONTAB_FILE ] ; then
  crontab -u $CRONTAB_USER $CRONTAB_FILE
  #echo "`date` Update $CRONTAB_USER crontab." >> /var/www/logs/cron/cron.log
fi

